runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  login: admin

libraries:
- name: ssl
  version: latest

env_variables:
  CONSUMER_KEY: 'NRakIcmUOCWbogbPsnHySFK4Q'
  CONSUMER_SECRET: 'owhDurASz56POtXpzG8mnZFzkdX5Hb2XV6O3aoHktbmHvyQACs'
  ACCESS_TOKEN: '3039814004-mjCJdEaYjzQsc18CLr8kx1cKcjucoy7iFxaU0Pt'
  ACCESS_TOKEN_SECRET: 'MmQHM6ULTRbpPAuMzwDjNbuAAq5Rlk0juB3ksCcKoB95P'
  PROJECT: 'cloud-202303'
  DATASET: 'xxx'
  BUCKET: 'cloud-202303.appspot.com'
  TEMPLATE_NAME: 'cloud-202303-twproc_tmpl'
